/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define RCC_BASE   0x40021000
#define PORTA_BASE 0x40010800

#define RCC_APB2ENR   *((volatile int *)( RCC_BASE   + 0x18))

#define RCC_CFGR  *((volatile int *)( RCC_BASE   + 0x04))
#define RCC_CR  *((volatile int *)( RCC_BASE   + 0x0))

#define PORTA_CRH     *((volatile int *)( PORTA_BASE + 0x04))
#define PORTA_ODR     *((volatile int *)( PORTA_BASE + 0x0c))



int main(void)
{
    RCC_CFGR |= ((0b10) << 0);
        RCC_CFGR |= ((0b0110) << 18);
        RCC_CFGR |= ((0b100) << 8);
        RCC_CFGR |= ((0b101) << 11);
        RCC_CR |= (1 << 24);
    volatile int i=0;
    RCC_APB2ENR |=1<<2;
	  RCC_APB2ENR |=1<<2;

    PORTA_CRH &=0xff0fffff;
    PORTA_CRH |=0x00200000;
    while (1){

    	PORTA_ODR^=1<<13;
    	for(i=0;i<50000;i++);
    }
}
