/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
 /* ================= RCC REGISTERS ================= */
#include"my_typedef.h"


 /* Base address of RCC */
#define RCC_BASE   0x40021000

/* APB2 Peripheral Clock Enable Register */
#define RCC_APB2ENR   *((volatile uint32_t *)(RCC_BASE + 0x18))


/* ================= GPIOA REGISTERS ================= */

/* Base address of GPIOA */
#define PORTA_BASE 0x40010800

/* Configuration register for pins 0 → 7 */
#define PORTA_CRL  *((volatile uint32_t *)(PORTA_BASE + 0x00))

/* Configuration register for pins 8 → 15 */
#define PORTA_CRH  *((volatile uint32_t *)(PORTA_BASE + 0x04))

/* Output data register */
#define PORTA_ODR  *((volatile uint32_t *)(PORTA_BASE + 0x0C))


/* ================= EXTI REGISTERS ================= */

/* Base address of EXTI */
#define EXTI_BASE   0x40010400

/* Base address of AFIO */
#define AFIO_BASE   0x40010000

/* Interrupt mask register (enable/disable interrupt line) */
#define EXTI_IMR     *((volatile uint32_t *)(EXTI_BASE + 0x00))

/* Rising trigger selection register */
#define EXTI_RTSR    *((volatile uint32_t *)(EXTI_BASE + 0x08))

/* Pending register (used to clear interrupt flag) */
#define EXTI_PR      *((volatile uint32_t *)(EXTI_BASE + 0x14))

/* External interrupt configuration register */
#define AFIO_EXTICR1 *((volatile uint32_t *)(AFIO_BASE + 0x08))


/* ================= NVIC REGISTERS ================= */

/* Base address of NVIC */
#define NVIC_BASE  0xE000E100

/* Interrupt Set Enable Register */
#define NVIC_ISER0 *((volatile uint32_t *)(NVIC_BASE + 0x00))


/* ================= INTERRUPT INITIALIZATION ================= */

void interrupt_init()
{
	/* Connect EXTI0 line to PORTA (PA0) */
	AFIO_EXTICR1 =0;
	

	/* Select Rising Edge trigger */
	EXTI_RTSR |= (1 << 0);
	/* Enable interrupt for EXTI line 0 */
	EXTI_IMR |= (1 << 0);
	

	/* Enable EXTI0 interrupt in NVIC (interrupt number 6) */
	NVIC_ISER0 |= (1 << 6);
}


/* ================= CLOCK INITIALIZATION ================= */

void clock_init()
{
	/* Enable clock for GPIOA */
	RCC_APB2ENR |= (1 << 2);

	/* Enable clock for AFIO (needed for EXTI mapping) */
	RCC_APB2ENR |= (1 << 0);
}


/* ================= GPIO INITIALIZATION ================= */

void gpio_init()
{
	PORTA_CRL &= ~(0xF << 0); // Clear MODE0 & CNF0
	PORTA_CRL |= (0x8 << 0); // MODE0=00, CNF0=10 → Input Pull-down
	PORTA_ODR &= ~(1 << 0);   // Output=0 → activates pull-down
	PORTA_CRH &= 0xFF0FFFFF;

	PORTA_CRH |= 0x00200000;



}


/* ================= MAIN FUNCTION ================= */


int main(void)
{
	/* Initialize system clock for peripherals */
	clock_init();

	/* Initialize GPIO pins */
	gpio_init();

	
	/* Initialize external interrupt */
	interrupt_init();
	
	/* Infinite loop (CPU waits for interrupt) */
	while (1);
}


/* ================= EXTI0 INTERRUPT HANDLER ================= */

void EXTI0_IRQHandler(void)
{
	/* Toggle LED on PA13 */
	PORTA_ODR ^= (1 << 13);

	/* Clear interrupt pending flag */
	EXTI_PR |= (1 << 0);
}