/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include"GPIO.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* ================== Delay Function ================== */
void wait(int x)
{
    for (volatile int i = 0; i < x; i++)
    {
        for (volatile int j = 0; j < 250; j++)
        {
            /* NOP */
        }
    }
}

/* ================== GPIO Initialization ================== */
void GPIO_ConfigurePins(void)
{
    GPIO_Config_Pin_t button1 = {PORTA, GPIO_PIN1, GPIO_MODE_Input_FLO, GPIO_SPEED_10M};
    GPIO_Config_Pin_t button13 = {PORTA, GPIO_PIN13, GPIO_MODE_Input_FLO, GPIO_SPEED_10M};

    GPIO_Config_Pin_t led1 = {PORTB, GPIO_PIN1, GPIO_MODE_Output_OD, GPIO_SPEED_10M};
    GPIO_Config_Pin_t led13 = {PORTB, GPIO_PIN13, GPIO_MODE_Output_OD, GPIO_SPEED_10M};

    GPIO_InitPin(&button1);
    GPIO_InitPin(&button13);
    GPIO_InitPin(&led1);
    GPIO_InitPin(&led13);
}

/* ================== Handle Single Press Button ================== */
void HandleButton1(void)
{
    uint8_t pin_state;
    GPIO_ReadPin(PORTA, GPIO_PIN1, &pin_state);

    if (pin_state == GPIO_LOW)
    {
        GPIO_TogglePin(PORTB, GPIO_PIN1);

        /* Wait until button released */
        do
        {
            GPIO_ReadPin(PORTA, GPIO_PIN1, &pin_state);
        } while (pin_state == GPIO_LOW);
    }
}

/* ================== Handle Multi Press Button ================== */
void HandleButton13(void)
{
    uint8_t pin_state;
    GPIO_ReadPin(PORTA, GPIO_PIN13, &pin_state);

    if (pin_state == GPIO_HIGH)
    {
        GPIO_TogglePin(PORTB, GPIO_PIN13);
    }
}

/* ================== Main Function ================== */
int main(void)
{
    GPIO_ConfigurePins(); /* Initialize GPIO pins */

    while (1)
    {
        HandleButton1();
        HandleButton13();
        wait(500);
    }
}
