/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
 /* ================= RCC REGISTERS ================= */
#include <stdint.h>

 /* Base address of RCC */
#define RCC_BASE   0x40021000

/* APB2 Peripheral Clock Enable Register */
#define RCC_APB2ENR   *((volatile uint32_t *)(RCC_BASE + 0x18))


/* ================= GPIOA REGISTERS ================= */

/* Base address of GPIOA */
#define PORTA_BASE    0x40010800

/* Configuration register for pins 0 → 7 */
#define PORTA_CRL  *((volatile uint32_t *)(PORTA_BASE + 0x00))

/* Configuration register for pins 8 → 15 */
#define PORTA_CRH  *((volatile uint32_t *)(PORTA_BASE + 0x04))

/* input data register */
#define PORTA_IDR  *((volatile uint32_t *)(PORTA_BASE + 0x08))

/* Output data register */
#define PORTA_ODR  *((volatile uint32_t *)(PORTA_BASE + 0x0C))

/* Base address of GPIOB */
#define PORTB_BASE   0x40010C00

/* Configuration register for pins 0 → 7 */
#define PORTB_CRL  *((volatile uint32_t *)(PORTB_BASE + 0x00))

/* Configuration register for pins 8 → 15 */
#define PORTB_CRH  *((volatile uint32_t *)(PORTB_BASE + 0x04))

/* input data register */
#define PORTB_IDR  *((volatile uint32_t *)(PORTB_BASE + 0x08))

/* Output data register */
#define PORTB_ODR  *((volatile uint32_t *)(PORTB_BASE + 0x0C))




/* ================= delay FUNCTION ================= */
void wait(int x) {
	for (volatile int i = 0; i < x; i++)
	{
		for (volatile int j = 0; j < 250; j++)
		{
			/*Nothing*/
		}

	}
}


/* ================= CLOCK INITIALIZATION ================= */

void clock_init()
{
	/* Enable clock for GPIOA */
	RCC_APB2ENR |= (1 << 2);

	/* Enable clock for GPIOB */
	RCC_APB2ENR |= (1<<3);
}


/* ================= GPIO INITIALIZATION ================= */

void gpio_init()
{
	//pin A1 single time button to pin B1 led  >> A1 input highz B1 output push/pull
	//pin A13 multi time button to pin B13 led >> A13 input highz B13 output push/pull

	// make A1 highZ input 
	PORTA_CRL = 0;   // clear
	PORTA_CRL |=(1 <<6);   // input floating

	// make A13 highZ input 
	PORTA_CRH = 0; 
	PORTA_CRH |= (1 << 22);


	// make B1  output push/pull
	PORTB_CRL = 0;
	PORTB_CRL |= (1 << 4);   // output push pull 10MHz

	// make B13 output push/pull 
	PORTB_CRH =0;
	PORTB_CRH |= (1 << 20);


}

/* ================= MAIN FUNCTION ================= */


int main(void)
{
	/* Initialize system clock for peripherals */
	clock_init();

	/* Initialize GPIO pins */
	gpio_init();


	while (1) {

		if ((((PORTA_IDR & (1 << 1))>>1))==0)
		{
			PORTB_ODR ^= (1 << 1);
			while (((((PORTA_IDR & (1 << 1)) >> 1)) == 0));
		}

		if ((PORTA_IDR & (1 << 13))>>13)
		{
			PORTB_ODR ^= (1 << 13);
			
		}

		wait(20000);
	}
	
}